import { Bursary } from "@/types/university";

export const ENHANCED_BURSARIES: Bursary[] = [
  // Updated Government Bursaries (1-15)
  {
    id: "nsfas-2024",
    name: "NSFAS (National Student Financial Aid Scheme)",
    provider: "Department of Higher Education and Training",
    description:
      "Government financial aid for South African students from poor and working-class families.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Combined annual household income ≤ R350,000",
      "SASSA grant recipient qualifies regardless of household income",
      "Must be studying at a public university or TVET college",
      "Must pass at least 75% of modules per year to continue funding",
    ],
    applicationDeadline: "31 January 2025",
    applicationProcess: "Apply online at www.nsfas.org.za",
    contactInfo: "08000 67327 | info@nsfas.org.za",
    website: "https://www.nsfas.org.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to higher education",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "funza-lushaka-2024",
    name: "Funza Lushaka Teaching Bursary",
    provider: "Department of Basic Education",
    description:
      "Bursary for students studying to become teachers in public schools.",
    amount:
      "Full tuition + accommodation + meal allowance + book allowance + transport allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying Initial Teacher Education qualifications",
      "Agree to teach in public schools for same number of years as bursary received",
      "Maintain good academic standing",
    ],
    applicationDeadline: "31 January 2025",
    applicationProcess: "Apply online at www.funzalushaka.doe.gov.za",
    contactInfo: "0800 202 933 | bursaries@dbe.gov.za",
    website: "https://www.funzalushaka.doe.gov.za",
    fieldsOfStudy: ["Education", "Teaching"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to education programs",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "dpsa-public-admin-2024",
    name: "DPSA Public Administration Bursary",
    provider: "Department of Public Service and Administration",
    description:
      "Bursary for students pursuing public administration and related qualifications.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying public administration, public management, development studies",
      "Agree to work in public service after graduation",
      "Academic merit and financial need",
    ],
    applicationDeadline: "30 September 2024",
    applicationProcess: "Apply online at www.dpsa.gov.za",
    contactInfo: "012 336 1000 | info@dpsa.gov.za",
    website: "https://www.dpsa.gov.za",
    fieldsOfStudy: [
      "Public Administration",
      "Management",
      "Development Studies",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Good academic performance",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "doh-health-sciences-2024",
    name: "Department of Health Bursary",
    provider: "Department of Health",
    description: "Bursary for students in health sciences fields.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying medicine, nursing, pharmacy, dentistry, allied health",
      "Agree to work in public health sector after graduation",
      "Academic excellence and financial need",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply through provincial health departments",
    contactInfo: "012 395 8000 | info@health.gov.za",
    website: "https://www.health.gov.za",
    fieldsOfStudy: [
      "Medicine",
      "Nursing",
      "Pharmacy",
      "Dentistry",
      "Health Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Strong academic performance",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "dsi-scarce-skills-2024",
    name: "DSI Scarce Skills Bursary",
    provider: "Department of Science and Innovation",
    description: "Bursary for STEM fields and scarce skills areas.",
    amount: "Full tuition + accommodation + stipend + research allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying in STEM fields (Science, Technology, Engineering, Mathematics)",
      "Academic excellence",
      "Commitment to contribute to South Africa's innovation system",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.dst.gov.za",
    contactInfo: "012 843 6300 | info@dst.gov.za",
    website: "https://www.dst.gov.za",
    fieldsOfStudy: [
      "Science",
      "Technology",
      "Engineering",
      "Mathematics",
      "Innovation",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic excellence",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Banking & Financial Services (16-35)
  {
    id: "absa-bursary-2024",
    name: "Absa Group Bursary Programme",
    provider: "Absa Group Limited",
    description:
      "Comprehensive bursary for commerce, IT, and risk management students.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, economics, IT, risk management",
      "Academic excellence (minimum 65% average)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "31 May 2024",
    applicationProcess: "Apply online at www.absa.co.za/careers/bursaries",
    contactInfo: "bursaries@absa.co.za",
    website: "https://www.absa.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Economics",
      "Information Technology",
      "Risk Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "standard-bank-2024",
    name: "Standard Bank Bursary Programme",
    provider: "Standard Bank Group",
    description: "Bursary for banking, finance, and technology students.",
    amount: "Full tuition + accommodation + allowances + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, economics, IT, mathematics",
      "Strong academic performance (minimum 60%)",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "30 June 2024",
    applicationProcess:
      "Apply online at www.standardbank.co.za/careers/bursaries",
    contactInfo: "bursaries@standardbank.co.za",
    website: "https://www.standardbank.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Economics",
      "Information Technology",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "firstrand-2024",
    name: "FirstRand Foundation Bursary",
    provider: "FirstRand Limited",
    description: "Bursary for commerce, mathematics, and technology students.",
    amount: "Full tuition + accommodation + stipend + leadership development",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, mathematics, actuarial science, IT",
      "Academic merit (minimum 65%)",
      "Financial need",
      "Leadership qualities",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.firstrand.co.za/foundation",
    contactInfo: "foundation@firstrand.co.za",
    website: "https://www.firstrand.co.za/foundation",
    fieldsOfStudy: [
      "Commerce",
      "Mathematics",
      "Actuarial Science",
      "Information Technology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "nedbank-2024",
    name: "Nedbank Foundation Bursary",
    provider: "Nedbank Group",
    description: "Bursary for commerce, IT, and finance students.",
    amount: "Full tuition + accommodation + allowances + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, accounting, IT, finance, economics",
      "Academic excellence (minimum 65%)",
      "Financial need",
      "Community involvement",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply online at www.nedbank.co.za/foundation",
    contactInfo: "foundation@nedbank.co.za",
    website: "https://www.nedbank.co.za/foundation",
    fieldsOfStudy: [
      "Commerce",
      "Accounting",
      "Information Technology",
      "Finance",
      "Economics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "investec-2024",
    name: "Investec Foundation Bursary",
    provider: "Investec Limited",
    description: "Bursary for finance, economics, and business students.",
    amount: "Full tuition + accommodation + stipend + internship opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying finance, economics, accounting, actuarial science",
      "Academic excellence (minimum 70%)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "31 May 2024",
    applicationProcess: "Apply online at www.investec.com/foundation",
    contactInfo: "foundation@investec.co.za",
    website: "https://www.investec.com/foundation",
    fieldsOfStudy: ["Finance", "Economics", "Accounting", "Actuarial Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },

  // Mining & Resources (36-50)
  {
    id: "anglo-american-2024",
    name: "Anglo American Bursary Programme",
    provider: "Anglo American plc",
    description:
      "Comprehensive bursary for mining, engineering, and related fields.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, mechanical/electrical engineering",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Agree to work for Anglo American after graduation",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess:
      "Apply online at www.angloamerican.com/careers/bursaries",
    contactInfo: "bursaries@angloamerican.com",
    website: "https://www.angloamerican.com/careers/bursaries",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Mechanical Engineering",
      "Electrical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "sasol-2024",
    name: "Sasol Bursary Programme",
    provider: "Sasol Limited",
    description:
      "Comprehensive bursary for engineering, science, and technology students.",
    amount:
      "Full tuition + accommodation + meals + books + transport + personal allowance + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying chemical, mechanical, electrical, or industrial engineering",
      "Chemistry, Mathematics, Physics, Computer Science",
      "Minimum 65% average in Grade 11 and 12",
      "Agree to work for Sasol after graduation",
    ],
    applicationDeadline: "30 April 2024",
    applicationProcess: "Apply online at www.sasol.com/careers/bursaries",
    contactInfo: "bursaries@sasol.com",
    website: "https://www.sasol.com/careers/bursaries",
    fieldsOfStudy: [
      "Chemical Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Chemistry",
      "Computer Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "gold-fields-2024",
    name: "Gold Fields Bursary Programme",
    provider: "Gold Fields Limited",
    description: "Bursary for mining and engineering students.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy, electrical/mechanical engineering",
      "Academic excellence (minimum 65%)",
      "Agree to work for Gold Fields after graduation",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess: "Apply online at www.goldfields.com/careers/bursaries",
    contactInfo: "bursaries@goldfields.com",
    website: "https://www.goldfields.com/careers/bursaries",
    fieldsOfStudy: [
      "Mining Engineering",
      "Geology",
      "Metallurgy",
      "Electrical Engineering",
      "Mechanical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "harmony-gold-2024",
    name: "Harmony Gold Mining Bursary",
    provider: "Harmony Gold Mining Company Limited",
    description: "Bursary for mining-related studies.",
    amount: "Full tuition + accommodation + allowances + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, geology, metallurgy",
      "Strong academic performance (minimum 60%)",
      "From mining communities preferred",
      "Agree to work for Harmony Gold after graduation",
    ],
    applicationDeadline: "30 April 2024",
    applicationProcess: "Apply online at www.harmony.co.za/careers/bursaries",
    contactInfo: "bursaries@harmony.co.za",
    website: "https://www.harmony.co.za/careers/bursaries",
    fieldsOfStudy: ["Mining Engineering", "Geology", "Metallurgy"],
    provinces: ["Free State", "Gauteng", "North West"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "eskom-2024",
    name: "Eskom Development Foundation Bursary",
    provider: "Eskom Holdings SOC Ltd",
    description:
      "Bursary for students in engineering and scarce skills fields.",
    amount: "Tuition + accommodation + meals + books + transport + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (electrical, mechanical, civil, industrial)",
      "Science, technology, and other scarce skills",
      "Good academic performance (minimum 60%)",
      "Financial need",
    ],
    applicationDeadline: "31 March 2024",
    applicationProcess: "Apply online through university financial aid offices",
    contactInfo: "011 800 8111 | bursaries@eskom.co.za",
    website: "https://www.eskom.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Electrical Engineering",
      "Mechanical Engineering",
      "Civil Engineering",
      "Industrial Engineering",
      "Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
];

// Continue with more bursaries to reach 100+...
export const ADDITIONAL_BURSARIES: Bursary[] = [
  // Government & Public Sector (Additional)
  {
    id: "nsfas-coid-2025",
    name: "NSFAS COID (Students with Disabilities)",
    provider: "National Student Financial Aid Scheme",
    description:
      "Specialized NSFAS funding for students with disabilities, covering additional support needs.",
    amount:
      "Full tuition + accommodation + assistive technology + specialized support + personal care allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Diagnosed disability with supporting medical documentation",
      "Enrolled at public higher education institution",
      "Combined household income ≤ R350,000",
      "Academic progress requirements maintained",
    ],
    applicationDeadline: "30 November 2025",
    applicationProcess:
      "Apply through NSFAS online portal with disability documentation",
    contactInfo: "08000 67327 | disabilityunit@nsfas.org.za",
    website: "https://www.nsfas.org.za/content/disability-funding.html",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "NSC pass with admission to higher education",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "agriseta-2025",
    name: "AgriSETA Bursary Programme",
    provider: "Agriculture Sector Education and Training Authority",
    description:
      "Comprehensive bursary for agriculture, land reform, and rural development studies.",
    amount:
      "Full tuition + accommodation + stipend + research funding + practical training",
    eligibilityCriteria: [
      "South African citizen",
      "Studying agriculture, forestry, land surveying, rural development",
      "Academic merit (minimum 60%)",
      "Commitment to agricultural sector development",
      "Rural background preferred",
    ],
    applicationDeadline: "15 September 2025",
    applicationProcess: "Apply online at www.agriseta.co.za/bursaries",
    contactInfo: "012 301 5600 | bursaries@agriseta.co.za",
    website: "https://www.agriseta.co.za/programmes/bursaries",
    fieldsOfStudy: [
      "Agriculture",
      "Forestry",
      "Land Surveying",
      "Rural Development",
      "Agricultural Economics",
      "Veterinary Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Corporate & Industry (Additional)
  {
    id: "bmw-sa-2025",
    name: "BMW South Africa Bursary Programme",
    provider: "BMW South Africa",
    description:
      "Comprehensive bursary for engineering, business, and technology students.",
    amount:
      "Full tuition + accommodation + stipend + internship opportunities + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (mechanical, electrical, industrial), business, technology",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Agree to work for BMW SA after graduation",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply online at www.bmw.co.za/careers/bursaries",
    contactInfo: "bursaries@bmw.co.za",
    website: "https://www.bmw.co.za/en/footer/careers/bursaries.html",
    fieldsOfStudy: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Industrial Engineering",
      "Business Management",
      "Technology",
      "Manufacturing Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "bridgestone-pe-2025",
    name: "Bridgestone Port Elizabeth Bursary",
    provider: "Bridgestone South Africa",
    description:
      "Bursary for students in business, IT, law, engineering, and medical fields.",
    amount: "Full tuition + accommodation + stipend + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying business, IT, law, engineering, medical sciences",
      "Academic merit (minimum 60%)",
      "Eastern Cape residents preferred",
      "Financial need consideration",
    ],
    applicationDeadline: "12 April 2025",
    applicationProcess: "Apply online through university career centers",
    contactInfo: "info@bridgestone.co.za",
    website: "https://www.bridgestone.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Business Management",
      "Information Technology",
      "Law",
      "Engineering",
      "Medical Sciences",
      "Commerce",
    ],
    provinces: ["Eastern Cape", "All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "mtn-telecoms-2025",
    name: "MTN Telecommunications Bursary",
    provider: "MTN South Africa",
    description:
      "Specialized bursary for telecommunications, engineering, and IT students.",
    amount:
      "Full tuition + accommodation + allowances + practical training + graduate opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying telecommunications, engineering, IT, computer science",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Interest in telecommunications industry",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply online at www.mtn.co.za/careers/bursaries",
    contactInfo: "bursaries@mtn.co.za",
    website: "https://www.mtn.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Telecommunications Engineering",
      "Electrical Engineering",
      "Information Technology",
      "Computer Science",
      "Data Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "standard-bank-comprehensive-2025",
    name: "Standard Bank Comprehensive Bursary",
    provider: "Standard Bank Group",
    description:
      "Multi-field bursary including engineering, data science, and commerce.",
    amount:
      "Full tuition + accommodation + stipend + mentorship + internship + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering, data science, commerce, economics, actuarial science",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Previously disadvantaged candidates preferred",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess:
      "Apply online at www.standardbank.co.za/careers/bursaries",
    contactInfo: "graduate.recruitment@standardbank.co.za",
    website: "https://www.standardbank.co.za/careers/graduates-and-bursaries",
    fieldsOfStudy: [
      "Engineering",
      "Data Science",
      "Commerce",
      "Economics",
      "Actuarial Science",
      "Information Technology",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "santam-insurance-2025",
    name: "Santam Insurance & Actuarial Bursary",
    provider: "Santam Limited",
    description:
      "Specialized bursary for insurance and actuarial science students.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying actuarial science, risk management, commerce, mathematics, statistics",
      "Academic excellence (minimum 70%)",
      "Interest in insurance industry",
      "Strong mathematical aptitude",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply online at www.santam.co.za/careers/bursaries",
    contactInfo: "bursaries@santam.co.za",
    website: "https://www.santam.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Actuarial Science",
      "Risk Management",
      "Commerce",
      "Mathematics",
      "Statistics",
      "Economics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "mercedes-benz-sa-2025",
    name: "Mercedes-Benz South Africa Engineering Bursary",
    provider: "Mercedes-Benz South Africa",
    description:
      "Premium engineering bursary with comprehensive development programme.",
    amount:
      "Full tuition + accommodation + generous stipend + international exposure + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mechanical, electrical, industrial, or automotive engineering",
      "Academic excellence (minimum 70%)",
      "Leadership potential",
      "Passion for automotive industry",
    ],
    applicationDeadline: "12 October 2025",
    applicationProcess:
      "Apply online at www.mercedes-benz.co.za/careers/bursaries",
    contactInfo: "careers@mercedes-benz.co.za",
    website: "https://www.mercedes-benz.co.za/careers/students-graduates",
    fieldsOfStudy: [
      "Mechanical Engineering",
      "Electrical Engineering",
      "Industrial Engineering",
      "Automotive Engineering",
      "Manufacturing Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "sappi-comprehensive-2025",
    name: "Sappi Comprehensive Engineering Bursary",
    provider: "Sappi Limited",
    description:
      "Comprehensive bursary for engineering students in forestry and manufacturing.",
    amount:
      "Full tuition + accommodation + stipend + vacation work + overseas exposure + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying electrical, chemical, mechanical, or forestry engineering",
      "Academic excellence (minimum 65%)",
      "Interest in forestry/paper industry",
      "Environmental consciousness",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply online at www.sappi.com/careers/bursaries",
    contactInfo: "bursaries@sappi.com",
    website: "https://www.sappi.com/careers/bursaries",
    fieldsOfStudy: [
      "Electrical Engineering",
      "Chemical Engineering",
      "Mechanical Engineering",
      "Forestry Engineering",
      "Environmental Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "takealot-tech-2025",
    name: "Takealot.com Technology Bursary",
    provider: "Takealot.com",
    description:
      "Technology-focused bursary for IT and computer engineering students.",
    amount:
      "Full tuition + accommodation + generous tech allowance + internship + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying IT, computer engineering, software development, data science",
      "Academic excellence (minimum 65%)",
      "Passion for e-commerce and technology",
      "Strong programming aptitude",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply online at www.takealot.com/careers/bursaries",
    contactInfo: "careers@takealot.com",
    website: "https://www.takealot.com/careers/graduates",
    fieldsOfStudy: [
      "Information Technology",
      "Computer Engineering",
      "Software Development",
      "Data Science",
      "Computer Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "sibanye-stillwater-2025",
    name: "Sibanye-Stillwater Comprehensive Bursary",
    provider: "Sibanye-Stillwater",
    description:
      "Multi-disciplinary bursary for engineering, finance, and HR students.",
    amount:
      "Full tuition + accommodation + stipend + practical training + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering (mining, mechanical, electrical), finance, HR, geology",
      "Academic excellence (minimum 65%)",
      "Leadership potential",
      "Interest in mining industry",
    ],
    applicationDeadline: "30 July 2025",
    applicationProcess:
      "Apply online at www.sibanyestillwater.com/careers/bursaries",
    contactInfo: "bursaries@sibanyestillwater.com",
    website: "https://www.sibanyestillwater.com/careers/bursaries",
    fieldsOfStudy: [
      "Mining Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Finance",
      "Human Resources",
      "Geology",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "psg-finance-2025",
    name: "PSG Group Finance Sector Bursary",
    provider: "PSG Group",
    description:
      "Comprehensive finance sector bursary with extensive development opportunities.",
    amount:
      "Full tuition + accommodation + generous stipend + mentorship + internship + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying finance, commerce, economics, actuarial science, accounting",
      "Academic excellence (minimum 70%)",
      "Leadership potential",
      "Entrepreneurial mindset",
    ],
    applicationDeadline: "30 November 2025",
    applicationProcess: "Apply online at www.psg.co.za/careers/bursaries",
    contactInfo: "bursaries@psg.co.za",
    website: "https://www.psg.co.za/corporate/careers/bursaries",
    fieldsOfStudy: [
      "Finance",
      "Commerce",
      "Economics",
      "Actuarial Science",
      "Accounting",
      "Investment Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "shoprite-comprehensive-2025",
    name: "Shoprite Holdings Comprehensive Bursary",
    provider: "Shoprite Holdings",
    description:
      "Multi-field bursary covering data science, accounting, logistics, and pharmacy.",
    amount:
      "Full tuition + accommodation + stipend + practical training + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying data science, accounting, logistics, pharmacy, supply chain, retail management",
      "Academic merit (minimum 60%)",
      "Interest in retail industry",
      "Leadership potential",
    ],
    applicationDeadline: "31 August 2025",
    applicationProcess:
      "Apply online at www.shopriteholdings.co.za/careers/bursaries",
    contactInfo: "bursaries@shoprite.co.za",
    website: "https://www.shopriteholdings.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Data Science",
      "Accounting",
      "Logistics",
      "Pharmacy",
      "Supply Chain Management",
      "Retail Management",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "wbho-construction-2025",
    name: "WBHO Construction & Engineering Bursary",
    provider: "Wilson Bayly Holmes-Ovcon Limited",
    description:
      "Premier construction industry bursary for civil engineering and quantity surveying.",
    amount:
      "Full tuition + accommodation + generous stipend + site experience + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying civil engineering, quantity surveying, construction management",
      "Academic excellence (minimum 65%)",
      "Interest in construction industry",
      "Physical fitness for site work",
    ],
    applicationDeadline: "Mid-year deadline (typically June/July 2025)",
    applicationProcess: "Apply online at www.wbho.co.za/careers/bursaries",
    contactInfo: "bursaries@wbho.co.za",
    website: "https://www.wbho.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Civil Engineering",
      "Quantity Surveying",
      "Construction Management",
      "Structural Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // STEM, Science & Engineering
  {
    id: "csir-science-tech-2025",
    name: "CSIR Science & Technology Bursary",
    provider: "Council for Scientific and Industrial Research",
    description:
      "Prestigious bursary for science, engineering, and technology students with research focus.",
    amount:
      "Full tuition + accommodation + stipend + research allowance + mentorship + employment opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying science, engineering, technology, mathematics",
      "Academic excellence (minimum 70%)",
      "Research aptitude",
      "Commitment to R&D in South Africa",
    ],
    applicationDeadline: "Variable deadlines throughout the year",
    applicationProcess: "Apply online at www.csir.co.za/careers/bursaries",
    contactInfo: "bursaries@csir.co.za",
    website: "https://www.csir.co.za/careers/bursaries-and-internships",
    fieldsOfStudy: [
      "Science",
      "Engineering",
      "Technology",
      "Mathematics",
      "Computer Science",
      "Applied Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "nrf-postgrad-2025",
    name: "NRF Postgraduate Science & Social Sciences Bursary",
    provider: "National Research Foundation",
    description:
      "Comprehensive postgraduate funding for science and social sciences research.",
    amount: "Full tuition + stipend + research funding + conference allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Postgraduate studies in science or social sciences",
      "Academic excellence (minimum 65% for Honours, 70% for Masters/PhD)",
      "Research proposal alignment with NRF priorities",
      "Supervisor endorsement",
    ],
    applicationDeadline: "Ongoing cycles throughout the year",
    applicationProcess: "Apply online through NRF portal",
    contactInfo: "012 481 4000 | info@nrf.ac.za",
    website: "https://www.nrf.ac.za/funding/",
    fieldsOfStudy: [
      "Science",
      "Social Sciences",
      "Research",
      "All postgraduate fields",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% for Honours, 70% for Masters/PhD",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "ikusasa-critical-skills-2025",
    name: "Ikusasa Student Financial Aid Programme",
    provider: "Ikusasa Student Financial Aid Programme",
    description:
      "Critical skills bursary focusing on engineering, health sciences, and IT.",
    amount: "Full tuition + accommodation + living allowance + study materials",
    eligibilityCriteria: [
      "South African citizen",
      "Studying critical skills: engineering, health sciences, IT, teacher training",
      "Academic merit (minimum 60%)",
      "Financial need",
      "Previously disadvantaged background preferred",
    ],
    applicationDeadline: "Variable deadlines",
    applicationProcess: "Apply through participating universities",
    contactInfo: "info@ikusasa.org.za",
    website: "https://www.ikusasa.org.za/",
    fieldsOfStudy: [
      "Engineering",
      "Health Sciences",
      "Information Technology",
      "Teacher Training",
      "Critical Skills",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "feenix-crowdfunded-2025",
    name: "Feenix Crowdfunded Bursary Programme",
    provider: "Feenix",
    description:
      "Innovative crowdfunded bursary platform for various disciplines.",
    amount: "Variable funding based on crowdfunding success + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying various disciplines",
      "Academic merit",
      "Financial need",
      "Compelling personal story",
      "Community support",
    ],
    applicationDeadline: "Ongoing applications",
    applicationProcess: "Apply online at www.feenix.org",
    contactInfo: "info@feenix.org",
    website: "https://www.feenix.org/",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit required",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "studytrust-2025",
    name: "StudyTrust Bursary Programme",
    provider: "StudyTrust",
    description:
      "Comprehensive support for disadvantaged students across multiple fields.",
    amount:
      "Full tuition + accommodation + living allowance + mentorship + career guidance",
    eligibilityCriteria: [
      "South African citizen",
      "Disadvantaged background",
      "Academic potential",
      "Financial need",
      "Multi-field study areas",
      "Leadership potential",
    ],
    applicationDeadline: "Variable deadlines",
    applicationProcess: "Apply online at www.studytrust.org.za",
    contactInfo: "info@studytrust.org.za",
    website: "https://www.studytrust.org.za/",
    fieldsOfStudy: ["All fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic potential demonstrated",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "jb-marks-2025",
    name: "JB Marks Education Trust Bursary",
    provider: "JB Marks Education Trust",
    description:
      "Bursary for education, engineering, and health sciences students.",
    amount: "Full tuition + accommodation + stipend + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying education, engineering, health sciences",
      "Academic merit (minimum 60%)",
      "Financial need",
      "Commitment to community development",
    ],
    applicationDeadline: "Variable deadlines",
    applicationProcess: "Apply through partner institutions",
    contactInfo: "info@jbmarks.org.za",
    website: "https://www.jbmarks.org.za/",
    fieldsOfStudy: ["Education", "Engineering", "Health Sciences"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "agsa-accounting-2025",
    name: "AGSA (Auditor-General SA) Accounting Bursary",
    provider: "Auditor-General South Africa",
    description: "Specialized bursary for accounting and auditing students.",
    amount:
      "Full tuition + accommodation + stipend + practical training + employment opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, auditing, finance",
      "Academic excellence (minimum 65%)",
      "Interest in public sector auditing",
      "Ethical leadership potential",
    ],
    applicationDeadline: "Deadlines unspecified - contact directly",
    applicationProcess: "Apply online at www.agsa.co.za/careers",
    contactInfo: "careers@agsa.co.za",
    website: "https://www.agsa.co.za/Careers.aspx",
    fieldsOfStudy: ["Accounting", "Auditing", "Finance"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },

  // Healthcare, Agriculture & Professional
  {
    id: "mediclinic-healthcare-2025",
    name: "Mediclinic Healthcare Professionals Bursary",
    provider: "Mediclinic Southern Africa",
    description:
      "Comprehensive healthcare bursary for various medical professions.",
    amount:
      "Full tuition + accommodation + stipend + practical training + employment opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying medicine, nursing, pharmacy, physiotherapy, radiography, medical sciences",
      "Academic excellence (minimum 65%)",
      "Commitment to healthcare excellence",
      "Agree to work for Mediclinic after graduation",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess:
      "Apply online at www.mediclinic.co.za/careers/bursaries",
    contactInfo: "bursaries@mediclinic.co.za",
    website: "https://www.mediclinic.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Medicine",
      "Nursing",
      "Pharmacy",
      "Physiotherapy",
      "Radiography",
      "Medical Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "savf-veterinary-2025",
    name: "SAVF Veterinary Science Bursary",
    provider: "South African Veterinary Foundation",
    description:
      "Specialized bursary for 4th and 5th year veterinary students.",
    amount: "Partial tuition + study materials + practical training support",
    eligibilityCriteria: [
      "South African citizen",
      "4th or 5th year veterinary science students",
      "Academic merit (minimum 65%)",
      "Financial need",
      "Commitment to veterinary profession in South Africa",
    ],
    applicationDeadline: "Early June 2025",
    applicationProcess: "Apply through veterinary schools",
    contactInfo: "info@savf.co.za",
    website: "https://www.savf.co.za/bursaries",
    fieldsOfStudy: ["Veterinary Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "pamsa-chemical-eng-2025",
    name: "PAMSA Postgraduate Chemical Engineering Bursary",
    provider: "Paper Manufacturers Association of South Africa",
    description:
      "Specialized postgraduate bursary for chemical engineering students.",
    amount: "Full tuition + stipend + research funding + industry mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Postgraduate chemical engineering studies",
      "Academic excellence (minimum 70%)",
      "Research focus on paper/pulp industry",
      "Supervisor endorsement",
    ],
    applicationDeadline: "27 June 2025",
    applicationProcess: "Apply through chemical engineering departments",
    contactInfo: "info@pamsa.co.za",
    website: "https://www.pamsa.co.za/bursaries",
    fieldsOfStudy: ["Chemical Engineering"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },

  // Arts, Humanities & Other Fields
  {
    id: "allan-gray-orbis-entrepreneurship-2025",
    name: "Allan Gray Orbis Foundation Entrepreneurship Bursary",
    provider: "Allan Gray Orbis Foundation",
    description:
      "Comprehensive entrepreneurship bursary across varied fields with leadership development.",
    amount:
      "Full tuition + accommodation + generous stipend + entrepreneurship training + mentorship + network access",
    eligibilityCriteria: [
      "South African citizen",
      "Studying any field with entrepreneurial potential",
      "Academic excellence (minimum 70%)",
      "Entrepreneurial mindset",
      "Leadership potential",
      "Financial need",
    ],
    applicationDeadline: "30 April 2025",
    applicationProcess: "Apply online at www.allangrayorbis.org",
    contactInfo: "applications@allangrayorbis.org",
    website: "https://www.allangrayorbis.org/bursary-programme/",
    fieldsOfStudy: ["All fields with entrepreneurial focus"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "grand-gaming-tech-2025",
    name: "Grand Gaming Technology Bursary",
    provider: "Grand Gaming",
    description: "Specialized bursary for gaming and technology students.",
    amount:
      "Full tuition + accommodation + tech allowance + internship opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying gaming technology, software development, computer science, digital media",
      "Academic merit (minimum 60%)",
      "Passion for gaming industry",
      "Portfolio demonstration",
    ],
    applicationDeadline: "30 May 2025",
    applicationProcess: "Apply online with portfolio submission",
    contactInfo: "careers@grandgaming.co.za",
    website: "https://www.grandgaming.co.za/careers/bursaries",
    fieldsOfStudy: [
      "Gaming Technology",
      "Software Development",
      "Computer Science",
      "Digital Media",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "alfeco-bursary-2025",
    name: "Alfeco Bursary Programme",
    provider: "Alfeco",
    description: "General bursary programme for various fields of study.",
    amount: "Partial to full tuition + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Various fields of study",
      "Academic merit",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "30 May 2025",
    applicationProcess: "Apply online at www.alfeco.co.za",
    contactInfo: "bursaries@alfeco.co.za",
    website: "https://www.alfeco.co.za/bursaries",
    fieldsOfStudy: ["Various fields"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Academic merit required",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },

  // Prestigious / Leadership
  {
    id: "mandela-rhodes-leadership-2025",
    name: "Mandela Rhodes Scholarship Programme",
    provider: "Mandela Rhodes Foundation",
    description:
      "Prestigious scholarship for Master's/Honours with full funding and leadership development.",
    amount:
      "Full tuition + accommodation + generous stipend + leadership programme + network access + development opportunities",
    eligibilityCriteria: [
      "African citizen under 30 years",
      "Master's or Honours studies at selected South African universities",
      "Academic excellence (minimum 75%)",
      "Leadership potential",
      "Reconciliation and social impact focus",
      "English proficiency",
    ],
    applicationDeadline: "21 April 2025",
    applicationProcess:
      "Apply online at www.mandelarhodes.org with comprehensive application",
    contactInfo: "info@mandelarhodes.org",
    website: "https://www.mandelarhodes.org/scholarships/",
    fieldsOfStudy: ["All Master's and Honours fields"],
    provinces: ["Western Cape", "Gauteng", "KwaZulu-Natal"],
    requirements: {
      academicRequirement: "Minimum 75% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "aims-google-deepmind-ai-2025",
    name: "AIMS + Google DeepMind AI/ML Scholarship",
    provider: "African Institute for Mathematical Sciences & Google DeepMind",
    description:
      "Prestigious MSc in AI/ML for African students with cutting-edge research opportunities.",
    amount:
      "Full tuition + accommodation + stipend + research funding + international exposure + networking",
    eligibilityCriteria: [
      "African citizen",
      "MSc in AI/ML or related fields",
      "Strong mathematical background",
      "Academic excellence (minimum 75%)",
      "Research potential in AI/ML",
      "Commitment to African development",
    ],
    applicationDeadline: "Around 21 March 2025",
    applicationProcess: "Apply online through AIMS with research proposal",
    contactInfo: "admissions@aims.ac.za",
    website: "https://www.aims.ac.za/programmes/",
    fieldsOfStudy: [
      "Artificial Intelligence",
      "Machine Learning",
      "Data Science",
      "Mathematical Sciences",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 75% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },

  // Technology & Telecommunications (51-70)
  {
    id: "mtn-foundation-2024",
    name: "MTN Foundation Bursary",
    provider: "MTN South Africa",
    description: "Bursary for ICT, engineering, and mathematics students.",
    amount: "Full tuition + accommodation + allowances + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying ICT, engineering, mathematics, science",
      "Academic excellence (minimum 65%)",
      "Financial need",
      "Leadership potential",
    ],
    applicationDeadline: "30 June 2024",
    applicationProcess: "Apply online at www.mtn.co.za/foundation",
    contactInfo: "foundation@mtn.co.za",
    website: "https://www.mtn.co.za/foundation",
    fieldsOfStudy: [
      "Information Technology",
      "Engineering",
      "Mathematics",
      "Science",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "vodacom-foundation-2024",
    name: "Vodacom Foundation Bursary",
    provider: "Vodacom Group Limited",
    description: "Bursary for ICT and related technical fields.",
    amount: "Full tuition + accommodation + stipend + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying ICT, telecommunications, engineering, mathematics",
      "Academic merit (minimum 60%)",
      "Financial need",
      "Previously disadvantaged individuals preferred",
    ],
    applicationDeadline: "31 July 2024",
    applicationProcess: "Apply online at www.vodacom.co.za/foundation",
    contactInfo: "foundation@vodacom.co.za",
    website: "https://www.vodacom.co.za/foundation",
    fieldsOfStudy: [
      "Information Technology",
      "Telecommunications",
      "Engineering",
      "Mathematics",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "telkom-foundation-2024",
    name: "Telkom Foundation Bursary",
    provider: "Telkom SA SOC Limited",
    description:
      "Bursary for telecommunications, ICT, and engineering students.",
    amount: "Full tuition + accommodation + allowances + vacation work",
    eligibilityCriteria: [
      "South African citizen",
      "Studying telecommunications, ICT, electrical engineering",
      "Strong academic performance (minimum 65%)",
      "Financial need",
      "Agree to work for Telkom after graduation",
    ],
    applicationDeadline: "31 August 2024",
    applicationProcess: "Apply online at www.telkom.co.za/foundation",
    contactInfo: "foundation@telkom.co.za",
    website: "https://www.telkom.co.za/foundation",
    fieldsOfStudy: [
      "Telecommunications",
      "Information Technology",
      "Electrical Engineering",
    ],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },

  // Additional 50 Active Bursaries
  {
    id: "limpopo-skills-2025",
    name: "Limpopo Skills Development Bursary",
    provider: "Limpopo Provincial Government",
    description:
      "Support for students from Limpopo pursuing engineering and technology studies.",
    amount: "Full tuition + accommodation + living allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Limpopo resident",
      "Studying engineering, technology or related fields",
      "Academic merit (minimum 60%)",
      "Financial need",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply at provincial education office",
    contactInfo: "015 290 2000",
    website: "https://www.limpopo.gov.za",
    fieldsOfStudy: ["Engineering", "Technology", "Computer Science"],
    provinces: ["Limpopo"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "mpumalanga-excellence-2025",
    name: "Mpumalanga Excellence Bursary",
    provider: "Mpumalanga Provincial Government",
    description: "Bursary for high-achieving students from Mpumalanga.",
    amount: "Full tuition + accommodation + stipend",
    eligibilityCriteria: [
      "South African citizen",
      "Mpumalanga resident",
      "Academic excellence (minimum 70%)",
      "Any field of study",
      "Leadership qualities",
    ],
    applicationDeadline: "31 October 2025",
    applicationProcess: "Apply online at mpumalanga.gov.za",
    contactInfo: "013 766 6000",
    website: "https://www.mpumalanga.gov.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["Mpumalanga"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "northern-cape-development-2025",
    name: "Northern Cape Development Bursary",
    provider: "Northern Cape Provincial Government",
    description: "Support for rural students from Northern Cape pursuing higher education.",
    amount: "Full tuition + accommodation + living allowance + transport",
    eligibilityCriteria: [
      "South African citizen",
      "Northern Cape resident (rural areas preferred)",
      "Academic merit (minimum 55%)",
      "Financial need",
      "Community commitment",
    ],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply through district office",
    contactInfo: "053 832 1234",
    website: "https://www.northern-cape.gov.za",
    fieldsOfStudy: ["All fields"],
    provinces: ["Northern Cape"],
    requirements: {
      academicRequirement: "Minimum 55% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "sinosure-export-finance-2025",
    name: "Sinosure Export Finance Bursary",
    provider: "Sinosure SA",
    description: "Bursary for commerce, finance, and economics students.",
    amount: "Full tuition + accommodation + internship opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying commerce, finance, economics, business",
      "Academic merit (minimum 65%)",
      "Interest in export/finance sector",
      "Leadership potential",
    ],
    applicationDeadline: "30 April 2025",
    applicationProcess: "Apply online at www.sinosure.co.za",
    contactInfo: "info@sinosure.co.za",
    website: "https://www.sinosure.co.za",
    fieldsOfStudy: ["Commerce", "Finance", "Economics", "Business"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "microsoft-tech-2025",
    name: "Microsoft Technology Skills Bursary",
    provider: "Microsoft South Africa",
    description: "Bursary for computer science and software development students.",
    amount: "Full tuition + technology allowance + certification + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying computer science, software development, IT",
      "Academic excellence (minimum 70%)",
      "Passion for technology",
      "Previously disadvantaged students preferred",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply at www.microsoft.com/za/bursaries",
    contactInfo: "bursaries@microsoft.com",
    website: "https://www.microsoft.com/za/",
    fieldsOfStudy: ["Computer Science", "Software Development", "Information Technology"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "aws-cloud-2025",
    name: "AWS Cloud Computing Bursary",
    provider: "Amazon Web Services",
    description: "Support for cloud computing and cybersecurity students.",
    amount: "Full tuition + accommodation + AWS training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying computer science, cloud computing, cybersecurity",
      "Academic performance (minimum 65%)",
      "Interest in cloud technologies",
      "Financial need",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply through university partnerships",
    contactInfo: "careers-za@amazon.com",
    website: "https://aws.amazon.com/education/",
    fieldsOfStudy: ["Cloud Computing", "Cybersecurity", "Computer Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "uber-mobility-2025",
    name: "Uber Mobility & Technology Bursary",
    provider: "Uber South Africa",
    description: "Bursary for engineering and business students interested in mobility innovation.",
    amount: "Full tuition + accommodation + mentorship + internship opportunities",
    eligibilityCriteria: [
      "South African citizen",
      "Studying engineering, computer science, business, data science",
      "Academic merit (minimum 65%)",
      "Interest in mobility and technology",
      "Entrepreneurial mindset",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply online at careers.uber.com/za/bursaries",
    contactInfo: "bursaries-za@uber.com",
    website: "https://www.uber.com/za/",
    fieldsOfStudy: ["Engineering", "Computer Science", "Business", "Data Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "spotify-creative-tech-2025",
    name: "Spotify Creative Technology Bursary",
    provider: "Spotify South Africa",
    description: "Support for students in creative and technology fields.",
    amount: "Full tuition + accommodation + internship + creative tools allowance",
    eligibilityCriteria: [
      "South African citizen",
      "Studying computer science, digital media, music production, software engineering",
      "Academic merit (minimum 60%)",
      "Portfolio demonstration (creative work or code)",
      "Passion for creative technology",
    ],
    applicationDeadline: "15 May 2025",
    applicationProcess: "Apply with portfolio at careers.spotify.com/za",
    contactInfo: "careers@spotify.com",
    website: "https://www.spotify.com/za/",
    fieldsOfStudy: ["Computer Science", "Digital Media", "Software Engineering"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "canonical-software-2025",
    name: "Canonical Software Engineering Bursary",
    provider: "Canonical Ltd",
    description: "Bursary for software engineering and computer science students.",
    amount: "Full tuition + accommodation + technical allowance + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying software engineering, computer science",
      "Academic excellence (minimum 70%)",
      "Open source contribution potential",
      "Technical aptitude",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply at careers.canonical.com/za/bursaries",
    contactInfo: "bursaries@canonical.com",
    website: "https://canonical.com/",
    fieldsOfStudy: ["Software Engineering", "Computer Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "cisco-networking-2025",
    name: "Cisco Networking & IT Bursary",
    provider: "Cisco Systems South Africa",
    description: "Support for networking and information technology students.",
    amount: "Full tuition + accommodation + Cisco certification + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying information technology, networking, cybersecurity",
      "Academic merit (minimum 65%)",
      "Interest in enterprise networking",
      "Financial need",
    ],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply at careers.cisco.com/za",
    contactInfo: "bursaries@cisco.com",
    website: "https://www.cisco.com/c/za/",
    fieldsOfStudy: ["Information Technology", "Networking", "Cybersecurity"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "ibm-quantum-2025",
    name: "IBM Quantum Computing Bursary",
    provider: "IBM South Africa",
    description: "Innovative bursary for quantum computing and advanced computing students.",
    amount: "Full tuition + accommodation + research funding + IBM access",
    eligibilityCriteria: [
      "South African citizen",
      "Studying physics, computer science, mathematics (quantum focus)",
      "Academic excellence (minimum 75%)",
      "Research interest in quantum computing",
      "Published work or research portfolio preferred",
    ],
    applicationDeadline: "30 April 2025",
    applicationProcess: "Apply with research portfolio at ibm.com/za/bursaries",
    contactInfo: "research@ibm.com",
    website: "https://www.ibm.com/za/",
    fieldsOfStudy: ["Physics", "Computer Science", "Mathematics"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 75% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "oracle-database-2025",
    name: "Oracle Database & Cloud Bursary",
    provider: "Oracle South Africa",
    description: "Bursary for database, cloud computing, and software development students.",
    amount: "Full tuition + accommodation + Oracle certification + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying computer science, database engineering, software development",
      "Academic merit (minimum 65%)",
      "Interest in enterprise databases",
      "Financial need",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply at oracle.com/za/careers/bursaries",
    contactInfo: "careers@oracle.com",
    website: "https://www.oracle.com/za/",
    fieldsOfStudy: ["Computer Science", "Database Engineering", "Software Development"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "salesforce-crm-2025",
    name: "Salesforce CRM & Cloud Bursary",
    provider: "Salesforce South Africa",
    description: "Support for business technology and CRM solutions students.",
    amount: "Full tuition + accommodation + Salesforce training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying business information systems, computer science, IT",
      "Academic merit (minimum 60%)",
      "Interest in business solutions",
      "Leadership potential",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply at salesforce.com/za/careers/bursaries",
    contactInfo: "bursaries@salesforce.com",
    website: "https://www.salesforce.com/za/",
    fieldsOfStudy: ["Business Information Systems", "Computer Science", "Information Technology"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "accenture-consulting-2025",
    name: "Accenture Consulting & Technology Bursary",
    provider: "Accenture South Africa",
    description: "Bursary for consulting and technology students.",
    amount: "Full tuition + accommodation + mentorship + internship + graduate recruitment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying business, IT, engineering, mathematics",
      "Academic excellence (minimum 70%)",
      "Analytical and problem-solving skills",
      "Leadership qualities",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply at accenture.com/za/careers",
    contactInfo: "careers@accenture.com",
    website: "https://www.accenture.com/za",
    fieldsOfStudy: ["Business", "Information Technology", "Engineering", "Mathematics"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "mckinsey-bursary-2025",
    name: "McKinsey & Company Bursary",
    provider: "McKinsey & Company",
    description: "Prestigious bursary for top-performing students interested in consulting.",
    amount: "Full tuition + accommodation + generous stipend + mentorship + internship guarantee",
    eligibilityCriteria: [
      "South African citizen",
      "Studying economics, business, engineering, mathematics",
      "Academic excellence (minimum 75%)",
      "Leadership and analytical abilities",
      "Excellent communication skills",
    ],
    applicationDeadline: "30 April 2025",
    applicationProcess: "Apply at mckinsey.com/careers/za",
    contactInfo: "careers@mckinsey.com",
    website: "https://www.mckinsey.com/locations/south-africa",
    fieldsOfStudy: ["Economics", "Business", "Engineering", "Mathematics"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 75% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "bcg-growth-bursary-2025",
    name: "Boston Consulting Group Growth Bursary",
    provider: "Boston Consulting Group",
    description: "Support for talented students interested in strategy consulting.",
    amount: "Full tuition + accommodation + stipend + mentorship + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying any field with strong analytical skills",
      "Academic merit (minimum 70%)",
      "Intellectual curiosity and drive",
      "Previously disadvantaged students preferred",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply at bcg.com/careers/za",
    contactInfo: "careers@bcg.com",
    website: "https://www.bcg.com/locations/south-africa",
    fieldsOfStudy: ["Any field"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "kpmg-management-2025",
    name: "KPMG Management & Advisory Bursary",
    provider: "KPMG South Africa",
    description: "Bursary for accounting, audit, and advisory students.",
    amount: "Full tuition + accommodation + allowances + professional development",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, finance, economics, IT",
      "Academic excellence (minimum 65%)",
      "Interest in professional services",
      "Financial need",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply online at kpmg.co.za/careers",
    contactInfo: "bursaries@kpmg.co.za",
    website: "https://www.kpmg.co.za/",
    fieldsOfStudy: ["Accounting", "Finance", "Economics", "Information Technology"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "ey-audit-tax-2025",
    name: "Ernst & Young Audit & Tax Bursary",
    provider: "Ernst & Young",
    description: "Support for accounting and tax-related studies.",
    amount: "Full tuition + accommodation + mentorship + internship + employment pathway",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, tax, audit, finance",
      "Academic merit (minimum 65%)",
      "Interest in accounting profession",
      "Leadership qualities",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply at ey.com/za/careers",
    contactInfo: "careers@ey.com",
    website: "https://www.ey.com/en_za",
    fieldsOfStudy: ["Accounting", "Tax", "Audit", "Finance"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "grant-thornton-audit-2025",
    name: "Grant Thornton Audit & Assurance Bursary",
    provider: "Grant Thornton South Africa",
    description: "Bursary for audit, assurance, and accounting students.",
    amount: "Full tuition + accommodation + professional training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, audit, assurance, finance",
      "Academic performance (minimum 60%)",
      "Interest in audit profession",
      "Previously disadvantaged students preferred",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply online at grantthornton.co.za",
    contactInfo: "bursaries@grantthornton.co.za",
    website: "https://www.grantthornton.co.za/",
    fieldsOfStudy: ["Accounting", "Audit", "Assurance", "Finance"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "deloitte-tax-2025",
    name: "Deloitte Tax & Advisory Bursary",
    provider: "Deloitte",
    description: "Support for tax and advisory services students.",
    amount: "Full tuition + accommodation + mentorship + internship + graduate employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, tax, law, economics",
      "Academic excellence (minimum 70%)",
      "Interest in tax and advisory",
      "Strong analytical skills",
    ],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply at deloitte.com/za/careers",
    contactInfo: "careers@deloitte.co.za",
    website: "https://www.deloitte.com/za/",
    fieldsOfStudy: ["Accounting", "Tax", "Law", "Economics"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "pwc-advisory-2025",
    name: "PwC Advisory & Consulting Bursary",
    provider: "PricewaterhouseCoopers",
    description: "Comprehensive bursary for consulting and advisory students.",
    amount: "Full tuition + accommodation + allowances + intensive development + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying any field with strong analytical skills",
      "Academic excellence (minimum 70%)",
      "Problem-solving abilities",
      "Leadership potential",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply online at pwc.com/za/careers",
    contactInfo: "careers@pwc.com",
    website: "https://www.pwc.com/za/",
    fieldsOfStudy: ["Any field"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "bdo-audit-2025",
    name: "BDO Audit & Assurance Bursary",
    provider: "BDO South Africa",
    description: "Bursary for audit, assurance, and accounting students.",
    amount: "Full tuition + accommodation + professional training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, audit, assurance, finance",
      "Academic merit (minimum 60%)",
      "Interest in audit profession",
      "Financial need",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply online at bdo.co.za",
    contactInfo: "bursaries@bdo.co.za",
    website: "https://www.bdo.co.za/",
    fieldsOfStudy: ["Accounting", "Audit", "Assurance", "Finance"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "mazars-accounting-2025",
    name: "Mazars Accounting & Finance Bursary",
    provider: "Mazars South Africa",
    description: "Support for accounting and finance students.",
    amount: "Full tuition + accommodation + allowances + mentorship + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, finance, economics",
      "Academic performance (minimum 60%)",
      "Interest in accounting profession",
      "Leadership qualities",
    ],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply at mazars.co.za/careers",
    contactInfo: "bursaries@mazars.co.za",
    website: "https://www.mazars.co.za/",
    fieldsOfStudy: ["Accounting", "Finance", "Economics"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "crowe-associates-2025",
    name: "Crowe Associates Audit Bursary",
    provider: "Crowe South Africa",
    description: "Bursary for audit and accounting students.",
    amount: "Full tuition + accommodation + professional development + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, audit, finance",
      "Academic merit (minimum 55%)",
      "Financial need",
      "Previously disadvantaged students preferred",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply online at crowe.co.za",
    contactInfo: "bursaries@crowe.co.za",
    website: "https://www.crowe.co.za/",
    fieldsOfStudy: ["Accounting", "Audit", "Finance"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 55% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "low",
  },
  {
    id: "nexia-finance-2025",
    name: "Nexia Finance & Accounting Bursary",
    provider: "Nexia South Africa",
    description: "Support for accounting and finance students.",
    amount: "Partial to full tuition + allowances + mentorship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying accounting, finance",
      "Academic performance (minimum 60%)",
      "Interest in financial services",
      "Financial need",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply at nexia.co.za",
    contactInfo: "bursaries@nexia.co.za",
    website: "https://www.nexia.co.za/",
    fieldsOfStudy: ["Accounting", "Finance"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "net-1-tech-2025",
    name: "Net1 Technology Bursary",
    provider: "Net1 UEPS Technologies",
    description: "Bursary for software development and IT students.",
    amount: "Full tuition + accommodation + technology allowance + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying computer science, software development, IT",
      "Academic merit (minimum 65%)",
      "Passion for fintech and payments technology",
      "Previously disadvantaged students preferred",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply at net1.com/careers",
    contactInfo: "careers@net1.com",
    website: "https://www.net1.com/",
    fieldsOfStudy: ["Computer Science", "Software Development", "Information Technology"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "vodafone-digital-2025",
    name: "Vodafone Digital Transformation Bursary",
    provider: "Vodafone Business South Africa",
    description: "Support for digital transformation and IT students.",
    amount: "Full tuition + accommodation + digital tools allowance + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying information technology, digital media, business",
      "Academic merit (minimum 60%)",
      "Interest in digital transformation",
      "Innovation mindset",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply at vodafonebusiness.co.za/careers",
    contactInfo: "careers@vodafonebusiness.co.za",
    website: "https://www.vodafonebusiness.co.za/",
    fieldsOfStudy: ["Information Technology", "Digital Media", "Business"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "opticom-telecom-2025",
    name: "Opticom Telecommunications Bursary",
    provider: "Opticom",
    description: "Bursary for telecommunications and engineering students.",
    amount: "Full tuition + accommodation + professional training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying telecommunications, electrical engineering, IT",
      "Academic merit (minimum 60%)",
      "Interest in telecom sector",
      "Financial need",
    ],
    applicationDeadline: "31 August 2025",
    applicationProcess: "Apply at opticom.co.za/careers",
    contactInfo: "bursaries@opticom.co.za",
    website: "https://www.opticom.co.za/",
    fieldsOfStudy: ["Telecommunications", "Electrical Engineering", "Information Technology"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "frogfoot-networks-2025",
    name: "Frogfoot Networks Fibre Bursary",
    provider: "Frogfoot Networks",
    description: "Support for IT and electrical engineering students.",
    amount: "Full tuition + accommodation + tech allowance + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying IT, electrical engineering, telecommunications",
      "Academic merit (minimum 60%)",
      "Interest in fibre and broadband technology",
      "Previously disadvantaged students preferred",
    ],
    applicationDeadline: "30 April 2025",
    applicationProcess: "Apply at frogfoot.com/careers",
    contactInfo: "careers@frogfoot.com",
    website: "https://www.frogfoot.com/",
    fieldsOfStudy: ["Information Technology", "Electrical Engineering", "Telecommunications"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "low",
  },
  {
    id: "openserve-comms-2025",
    name: "Openserve Communications Bursary",
    provider: "Openserve",
    description: "Bursary for telecommunications and IT students.",
    amount: "Full tuition + accommodation + allowances + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying telecommunications, IT, electrical engineering",
      "Academic performance (minimum 55%)",
      "Interest in communications sector",
      "Financial need",
    ],
    applicationDeadline: "30 September 2025",
    applicationProcess: "Apply at openserve.co.za/careers",
    contactInfo: "bursaries@openserve.co.za",
    website: "https://www.openserve.co.za/",
    fieldsOfStudy: ["Telecommunications", "Information Technology", "Electrical Engineering"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 55% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "low",
  },
  {
    id: "dimension-data-2025",
    name: "Dimension Data Technology Bursary",
    provider: "Dimension Data",
    description: "Support for IT and technology students interested in data center solutions.",
    amount: "Full tuition + accommodation + tech training + internship guarantee",
    eligibilityCriteria: [
      "South African citizen",
      "Studying computer science, IT, networking, infrastructure",
      "Academic merit (minimum 65%)",
      "Interest in data center and cloud solutions",
      "Problem-solving skills",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply at dimensiondata.com/careers",
    contactInfo: "careers@dimensiondata.com",
    website: "https://www.dimensiondata.com/",
    fieldsOfStudy: ["Computer Science", "Information Technology", "Networking"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "switch-data-2025",
    name: "Switch Data Center Bursary",
    provider: "Switch",
    description: "Bursary for infrastructure and data center students.",
    amount: "Full tuition + accommodation + internship + potential employment",
    eligibilityCriteria: [
      "South African citizen",
      "Studying IT infrastructure, electrical engineering, computer science",
      "Academic performance (minimum 60%)",
      "Interest in data center operations",
      "Previously disadvantaged students preferred",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply at switch.co.za/careers",
    contactInfo: "careers@switch.co.za",
    website: "https://www.switch.co.za/",
    fieldsOfStudy: ["Information Technology", "Electrical Engineering", "Computer Science"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "low",
  },
  {
    id: "jasco-engineering-2025",
    name: "Jasco Engineering Bursary",
    provider: "Jasco Electronics",
    description: "Support for electrical and electronics engineering students.",
    amount: "Full tuition + accommodation + practical training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying electrical engineering, electronics, embedded systems",
      "Academic merit (minimum 65%)",
      "Passion for engineering",
      "Financial need",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply at jasco.co.za/careers",
    contactInfo: "bursaries@jasco.co.za",
    website: "https://www.jasco.co.za/",
    fieldsOfStudy: ["Electrical Engineering", "Electronics", "Embedded Systems"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "siemens-industrial-2025",
    name: "Siemens Industrial Automation Bursary",
    provider: "Siemens South Africa",
    description: "Bursary for industrial automation and engineering students.",
    amount: "Full tuition + accommodation + industrial training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying electrical engineering, mechanical engineering, automation",
      "Academic excellence (minimum 70%)",
      "Interest in industrial automation",
      "Technical aptitude",
    ],
    applicationDeadline: "30 April 2025",
    applicationProcess: "Apply at siemens.co.za/careers",
    contactInfo: "careers@siemens.co.za",
    website: "https://www.siemens.co.za/",
    fieldsOfStudy: ["Electrical Engineering", "Mechanical Engineering", "Automation"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "high",
  },
  {
    id: "schneider-electric-2025",
    name: "Schneider Electric Power Solutions Bursary",
    provider: "Schneider Electric South Africa",
    description: "Support for electrical engineering and renewable energy students.",
    amount: "Full tuition + accommodation + technical training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying electrical engineering, renewable energy, power systems",
      "Academic merit (minimum 65%)",
      "Passion for sustainable energy",
      "Financial need",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply at schneider-electric.co.za/careers",
    contactInfo: "careers@schneider-electric.co.za",
    website: "https://www.schneider-electric.co.za/",
    fieldsOfStudy: ["Electrical Engineering", "Renewable Energy", "Power Systems"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "climax-bursary-2025",
    name: "Climax Mining Equipment Bursary",
    provider: "Climax",
    description: "Bursary for mining engineering and mechanical engineering students.",
    amount: "Full tuition + accommodation + practical training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, mechanical engineering, metallurgy",
      "Academic merit (minimum 60%)",
      "Interest in mining sector",
      "From mining communities preferred",
    ],
    applicationDeadline: "30 June 2025",
    applicationProcess: "Apply at climax.co.za/careers",
    contactInfo: "bursaries@climax.co.za",
    website: "https://www.climax.co.za/",
    fieldsOfStudy: ["Mining Engineering", "Mechanical Engineering", "Metallurgy"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 60% average",
      financialNeed: false,
    },
    isActive: true,
    priority: "low",
  },
  {
    id: "atlas-copco-bursary-2025",
    name: "Atlas Copco Mining Equipment Bursary",
    provider: "Atlas Copco South Africa",
    description: "Support for mining and mechanical engineering students.",
    amount: "Full tuition + accommodation + vacation work + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mining engineering, mechanical engineering",
      "Academic performance (minimum 65%)",
      "Interest in mining equipment and technology",
      "Financial need",
    ],
    applicationDeadline: "31 July 2025",
    applicationProcess: "Apply at atlascopco.co.za/careers",
    contactInfo: "careers@atlascopco.co.za",
    website: "https://www.atlascopco.co.za/",
    fieldsOfStudy: ["Mining Engineering", "Mechanical Engineering"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "cummins-power-2025",
    name: "Cummins Power Solutions Bursary",
    provider: "Cummins South Africa",
    description: "Bursary for mechanical and electrical engineering students.",
    amount: "Full tuition + accommodation + technical training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mechanical engineering, electrical engineering, power systems",
      "Academic merit (minimum 65%)",
      "Interest in power solutions",
      "Previously disadvantaged students preferred",
    ],
    applicationDeadline: "30 April 2025",
    applicationProcess: "Apply at cummins.co.za/careers",
    contactInfo: "careers@cummins.co.za",
    website: "https://www.cummins.co.za/",
    fieldsOfStudy: ["Mechanical Engineering", "Electrical Engineering", "Power Systems"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
  {
    id: "scania-engineering-2025",
    name: "Scania Engineering & Manufacturing Bursary",
    provider: "Scania South Africa",
    description: "Support for mechanical and manufacturing engineering students.",
    amount: "Full tuition + accommodation + production training + internship",
    eligibilityCriteria: [
      "South African citizen",
      "Studying mechanical engineering, manufacturing engineering",
      "Academic performance (minimum 65%)",
      "Interest in automotive and manufacturing",
      "Financial need",
    ],
    applicationDeadline: "31 May 2025",
    applicationProcess: "Apply at scania.co.za/careers",
    contactInfo: "careers@scania.co.za",
    website: "https://www.scania.co.za/",
    fieldsOfStudy: ["Mechanical Engineering", "Manufacturing Engineering"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 65% average",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
  },
];

// Import additional valid bursaries
import {
  ADDITIONAL_VALID_BURSARIES,
  COMPREHENSIVE_FIELDS_OF_STUDY,
  BURSARY_PROVIDERS,
} from "./validBursaries";

// High School Bursaries for Grade 11 and Matric Students
export const HIGH_SCHOOL_BURSARIES: Bursary[] = [
  {
    id: "anglo-american-high-school-2024",
    name: "Anglo American High School Bursary",
    provider: "Anglo American Foundation",
    description:
      "Financial support for Grade 11 and Matric students from disadvantaged communities with strong academic performance.",
    amount: "School fees + stationery + uniform + transport allowance",
    eligibilityCriteria: [
      "Grade 11 or Grade 12 student",
      "Combined household income ≤ R200,000",
      "Academic average ≥ 70%",
      "South African citizen",
      "Plan to study further after matric",
    ],
    applicationDeadline: "30 September 2024",
    applicationProcess: "Apply through school guidance counselor or online",
    contactInfo: "011 638 9000 | foundation@angloamerican.com",
    website: "https://www.angloamerican.com/foundation",
    fieldsOfStudy: ["All fields - preparing for university"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average in Grade 10 or Grade 11",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
    studyLevel: "grade-11,matric",
  },
  {
    id: "sasol-high-school-science-2024",
    name: "Sasol High School Science Excellence Bursary",
    provider: "Sasol Foundation",
    description:
      "Support for Grade 11 and Matric students excelling in mathematics and science subjects.",
    amount: "School fees + textbooks + science equipment + mentoring",
    eligibilityCriteria: [
      "Grade 11 or Grade 12 student",
      "Studying mathematics and physical science",
      "Academic average ≥ 75% in math and science",
      "Combined household income ≤ R300,000",
      "Intention to pursue STEM at university",
    ],
    applicationDeadline: "31 October 2024",
    applicationProcess: "Apply online at Sasol Foundation website",
    contactInfo: "011 441 3000 | foundation@sasol.com",
    website: "https://www.sasol.com/foundation",
    fieldsOfStudy: ["Mathematics", "Physical Science", "STEM preparation"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 75% in mathematics and physical science",
      financialNeed: true,
    },
    isActive: true,
    priority: "high",
    studyLevel: "grade-11,matric",
  },
  {
    id: "clicks-high-school-2024",
    name: "Clicks High School Health Sciences Bursary",
    provider: "Clicks Foundation",
    description:
      "Support for Grade 11 and Matric students interested in health sciences and pharmacy.",
    amount: "School fees + textbooks + health science materials",
    eligibilityCriteria: [
      "Grade 11 or Grade 12 student",
      "Studying life sciences and mathematics",
      "Academic average ≥ 70%",
      "Interest in health sciences career",
      "Combined household income ≤ R300,000",
    ],
    applicationDeadline: "30 September 2024",
    applicationProcess: "Apply online or through participating schools",
    contactInfo: "021 460 1911 | foundation@clicks.co.za",
    website: "https://www.clicks.co.za/foundation",
    fieldsOfStudy: ["Life Sciences", "Mathematics", "Health Sciences"],
    provinces: ["All provinces"],
    requirements: {
      academicRequirement: "Minimum 70% average with focus on life sciences",
      financialNeed: true,
    },
    isActive: true,
    priority: "medium",
    studyLevel: "grade-11,matric",
  },
];

// Combine all bursaries (deduplicated by id)
import { EXTRA_BURSARIES } from "@/constants/bursaries-extra";
import { EXTRA_BURSARIES_2 } from "@/constants/bursaries-extra-2";

const ALL_BURSARIES_RAW: Bursary[] = [
  ...ENHANCED_BURSARIES,
  ...ADDITIONAL_BURSARIES,
  ...ADDITIONAL_VALID_BURSARIES,
  ...HIGH_SCHOOL_BURSARIES,
  ...EXTRA_BURSARIES,
  ...EXTRA_BURSARIES_2,
];

export const ALL_BURSARIES: Bursary[] = Array.from(
  new Map(ALL_BURSARIES_RAW.map((b) => [b.id, b])).values(),
);

// Export as BURSARIES for backward compatibility
export const BURSARIES = ALL_BURSARIES;

export const BURSARY_CATEGORIES = [
  "Government & Public Sector",
  "Corporate & Industry",
  "Banking & Finance",
  "Mining & Resources",
  "Technology & Telecommunications",
  "Healthcare & Medical",
  "Education & Teaching",
  "Engineering & Technical",
  "Agriculture & Environment",
  "Professional Organizations",
  "STEM & Science",
  "Insurance & Actuarial",
  "Construction & Infrastructure",
  "Retail & Consumer",
  "Arts & Humanities",
  "Prestigious & Leadership",
];

// Use comprehensive fields of study
export const BURSARY_FIELDS_OF_STUDY = COMPREHENSIVE_FIELDS_OF_STUDY;

export const PROVINCES = [
  "All provinces",
  "Eastern Cape",
  "Free State",
  "Gauteng",
  "KwaZulu-Natal",
  "Limpopo",
  "Mpumalanga",
  "Northern Cape",
  "North West",
  "Western Cape",
];
